services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    restart: unless-stopped
    hostname: diun
    command: serve
    volumes:
      - ${SERVICES}:/opt/services:ro
      - ${SERVICES}/diun/config/diun.yml:/diun.yml:ro
      - ${SERVICES}/diun/config/scripts:/data/scripts:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=info
      - LOG_JSON=false
    labels:
      - "diun.enable=true"

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}
