version: 2

updates:
  - package-ecosystem: "docker-compose"
    directories:
      - "/services/*"
    schedule:
      interval: "weekly"
    groups:
      actions-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "postgres"
        update-types: ["version-update:semver-major"]
