version: 2

updates:
  - package-ecosystem: "docker-compose"
    directories:
      - "/services/*"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "postgres"
        update-types: ["version-update:semver-major"]
