paseo-server.{$DOMAIN} {
	reverse_proxy dev:6767
}

paseo.{$DOMAIN} {

	basic_auth {
		{$BASICAUTH_USER} {$BASICAUTH_PASS}
	}
	reverse_proxy dev:6768
}

t3code.{$DOMAIN} {
	basic_auth {
		{$BASICAUTH_USER} {$BASICAUTH_PASS}
	}
	reverse_proxy dev:3773
}

opencode.{$DOMAIN} {
	reverse_proxy dev:4096
}

preview.{$DOMAIN} {
	reverse_proxy dev:5173
}

test.{$DOMAIN} {
	reverse_proxy dev:5173

	basic_auth {
		{$BASICAUTH_USER} {$BASICAUTH_PASS}
	}
}
