services:
  rss-bridge:
    image: rssbridge/rss-bridge:2025-08-05
    container_name: rss-bridge
    hostname: rss-bridge
    restart: unless-stopped
    volumes:
      - ${SERVICES}/rss-bridge/config:/config

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}
