services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    restart: unless-stopped
    hostname: homer
    environment:
      - TZ=${TZ}
    volumes:
      - ${SERVICES}/homer/config:/www/assets:ro

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}
