services:
  apprise:
    image: caronc/apprise:1.2.1
    hostname: apprise
    container_name: apprise
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - TZ=${TZ}
      - PGID=${PGID}
      - PASSWORD=${PASSWORD}
    volumes:
      - ${DATA}/apprise/config:/config

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}
