services:
  dockcheck-web:
    image: "palleri/dockcheck-web:latest"
    container_name: dockcheck-web
    restart: unless-stopped
    hostname: dockcheck-web
    volumes:
      - ${DATA}/dockcheck:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}