services:
  mind:
    image: mrcas/mind:latest
    hostname: mind
    container_name: mind
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - ${DATA}/mind/db:/app/db

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}