dev.{$DOMAIN} {
	reverse_proxy dev:6767
}

code.{$DOMAIN} {

	basic_auth {
		{$BASICAUTH_USER} {$BASICAUTH_PASS}
	}
	reverse_proxy dev:6768
}

test.{$DOMAIN} {
	reverse_proxy dev:5173

	basic_auth {
		{$BASICAUTH_USER} {$BASICAUTH_PASS}
	}
}
