services:
  wallabag:
    image: wallabag/wallabag:2.6.13
    container_name: wallabag
    hostname: wallabag
    restart: unless-stopped
    volumes:
      - ${DATA}/wallabag/data:/var/www/wallabag/data
      - ${DATA}/wallabag/images:/var/www/wallabag/web/assets/images
    environment:
      - SYMFONY__ENV__DOMAIN_NAME=https://research.${DOMAIN}
      - SYMFONY__ENV__FOSUSER_REGISTRATION=false
      - SYMFONY__ENV__FOSUSER_CONFIRMATION=false

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}
