name: Deploy to Server

on:
  push:
    branches: [master] # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 65.108.95.112
          username: arvigeus
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/arvigeus/arvigeus.one

            # Check if repository is dirty (has uncommitted changes)
            if ! git diff-index --quiet HEAD --; then
              echo "ERROR: Repository has uncommitted changes!"
              echo "Uncommitted files:"
              git status --porcelain
              echo ""
              echo "Please commit or stash changes before deploying:"
              echo "  git add . && git commit -m 'Manual changes' && git push"
              echo "  OR: git stash"
              exit 1
            fi

            # Check if there are untracked files
            if [ -n "$(git ls-files --others --exclude-standard)" ]; then
              echo "WARNING: Repository has untracked files:"
              git ls-files --others --exclude-standard
              echo ""
              echo "Consider adding these files to .gitignore or committing them"
              echo "Continuing deployment..."
            fi

            # Fetch latest changes
            echo "Fetching latest changes..."
            git fetch origin master

            # Check if we're behind
            LOCAL=$(git rev-parse HEAD)
            REMOTE=$(git rev-parse origin/master)

            if [ "$LOCAL" = "$REMOTE" ]; then
              echo "Repository is already up to date"
              exit 0
            fi

            # Check what will change before pulling
            CHANGED_FILES=$(git diff --name-only HEAD origin/master)

            # Attempt to pull
            echo "Pulling changes..."
            if git pull origin master; then
              # Check if services directory was modified
              if echo "$CHANGED_FILES" | grep -q '^services/'; then
                echo "Services directory modified, pulling new images and restarting..."
                ./run.sh update
                echo "Services updated successfully!"
              else
                echo "No services changes detected, skipping restart"
              fi
              echo "Deployment successful!"
            else
              echo "Git pull failed - there may be merge conflicts"
              echo "Manual intervention required on server"
              exit 1
            fi
